CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS goals (
  id UUID PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  icon VARCHAR(256) NOT NULL,
  range INT4 NOT NULL,
  value INT4 NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- DROP TABLE users CASCADE;
-- DROP TABLE goals CASCADE;
