CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  emotion VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS goals (
  id UUID PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  icon VARCHAR(256) NOT NULL,
  range INT4 NOT NULL,
  value INT4 NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY,
  todo VARCHAR(256) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DROP TABLE users CASCADE;
-- DROP TABLE goals CASCADE;
-- DROP TABLE todos CASCADE;